"""change progress to status in project table

Revision ID: 4b716225ec53
Revises: 
Create Date: 2025-06-18 08:41:09.371471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b716225ec53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Float(), nullable=False))
        batch_op.drop_column('progress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.FLOAT(), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
