"""update models

Revision ID: a11be1cc484a
Revises: a1ef07d1b882
Create Date: 2025-06-19 21:27:20.080178

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a11be1cc484a"
down_revision = "a1ef07d1b882"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index("idx_categories_user_id", ["user_id"], unique=False)

    with op.batch_alter_table("lists", schema=None) as batch_op:
        batch_op.create_index("idx_lists_progress", ["progress"], unique=False)
        batch_op.create_index("idx_lists_project_id", ["project_id"], unique=False)

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index("idx_projects_status", ["status"], unique=False)
        batch_op.create_index("idx_projects_user_id", ["user_id"], unique=False)
        batch_op.create_index(
            "idx_projects_user_status", ["user_id", "status"], unique=False
        )

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "total_time_worked",
                sa.Integer(),
                nullable=False,
                comment="Cumulative minutes worked",
            )
        )
        batch_op.add_column(
            sa.Column(
                "current_work_start",
                sa.DateTime(timezone=True),
                nullable=True,
                comment="Current session start time",
            )
        )
        batch_op.add_column(
            sa.Column(
                "current_planned_end",
                sa.DateTime(timezone=True),
                nullable=True,
                comment="Current session planned end time",
            )
        )
        batch_op.add_column(
            sa.Column(
                "first_started_at",
                sa.DateTime(timezone=True),
                nullable=True,
                comment="When task was first started",
            )
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.VARCHAR(),
            type_=sa.Text(),
            existing_nullable=True,
        )
        batch_op.alter_column("category_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_index("idx_tasks_category_id", ["category_id"], unique=False)
        batch_op.create_index("idx_tasks_list_id", ["list_id"], unique=False)
        batch_op.create_index("idx_tasks_priority", ["priority"], unique=False)
        batch_op.create_index("idx_tasks_status", ["status"], unique=False)
        batch_op.create_index(
            "idx_tasks_status_list", ["status", "list_id"], unique=False
        )
        batch_op.drop_constraint("task", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "categories", ["category_id"], ["id"], ondelete="SET NULL"
        )
        batch_op.drop_column("started_at")
        batch_op.drop_column("actual_duration")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("actual_duration", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("started_at", sa.DATETIME(), nullable=True))
        batch_op.drop_constraint("task", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "categories", ["category_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_index("idx_tasks_status_list")
        batch_op.drop_index("idx_tasks_status")
        batch_op.drop_index("idx_tasks_priority")
        batch_op.drop_index("idx_tasks_list_id")
        batch_op.drop_index("idx_tasks_category_id")
        batch_op.alter_column("category_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.drop_column("first_started_at")
        batch_op.drop_column("current_planned_end")
        batch_op.drop_column("current_work_start")
        batch_op.drop_column("total_time_worked")

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index("idx_projects_user_status")
        batch_op.drop_index("idx_projects_user_id")
        batch_op.drop_index("idx_projects_status")

    with op.batch_alter_table("lists", schema=None) as batch_op:
        batch_op.drop_index("idx_lists_project_id")
        batch_op.drop_index("idx_lists_progress")

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index("idx_categories_user_id")

    # ### end Alembic commands ###
